### ISSUE TITLE
Fehler beim Einrichten

### ISSUE THREAD

**Issue by cosmicboy6** [platysma/hass-vienna-smartmeter#7] opened 2021-09-14 11:10 UTC
Logger: homeassistant.config_entries
Source: custom_components/vienna_smartmeter/api.py:50
Integration: Vienna Smart Meter (documentation, issues)
First occurred: 13. September 2021, 22:15:23 (1 occurrences)
Last logged: 13. September 2021, 22:15:23

Error setting up entry test@gmail.com for vienna_smartmeter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/vienna_smartmeter/__init__.py", line 47, in async_setup_entry
    await client._refresh_token()
  File "/config/custom_components/vienna_smartmeter/api.py", line 76, in _refresh_token
    "code": await self._get_auth_code(),
  File "/config/custom_components/vienna_smartmeter/api.py", line 55, in _get_auth_code
    action = await self._get_login_action()
  File "/config/custom_components/vienna_smartmeter/api.py", line 50, in _get_login_action
    tree = html.fromstring(resp.content)
  File "/usr/local/lib/python3.9/site-packages/lxml/html/__init__.py", line 874, in fromstring
    is_full_html = _looks_like_full_html_unicode(html)
TypeError: expected string or bytes-like object

**Comment by platysma** [comment] 2021-09-14 11:39
Duplicate of #2

**Closed** 2021-09-14 11:39 UTC
